### ISSUE TITLE
container stuck in a loop

### ISSUE THREAD

**Issue by bonkersGER** [ex0nuss/Remote-Wake-Sleep-On-LAN-Docker#1]
Hello i did try out your docker container but the container stuck in a loop

my docker-compose file

```
version: "3"

services:
  frontend-rwsols:
    image: ex0nuss/remote-wake-sleep-on-lan-docker
    container_name: frontend-rwsols
    restart: unless-stopped
    network_mode: host
    environment:
      - APACHE2_PORT=8080
      - PASSPHRASE=MYSECUREPASS
      - RWSOLS_COMPUTER_NAME="Plex Server"
      - RWSOLS_COMPUTER_MAC="D0:50:99:5C:59:EC"
      - RWSOLS_COMPUTER_IP="192.168.188.10"
```

Console output:

```
pi@rpi3-001:~/docker/wakeonlan $ sudo docker-compose up --force-recreate
Recreating frontend-rwsols ... done
Attaching to frontend-rwsols
frontend-rwsols    | standard_init_linux.go:219: exec user process caused: exec format error
frontend-rwsols exited with code 1
frontend-rwsols    | standard_init_linux.go:219: exec user process caused: exec format error
frontend-rwsols    | standard_init_linux.go:219: exec user process caused: exec format error
frontend-rwsols exited with code 1
frontend-rwsols    | standard_init_linux.go:219: exec user process caused: exec format error
frontend-rwsols    | standard_init_linux.go:219: exec user process caused: exec format error
frontend-rwsols    | standard_init_linux.go:219: exec user process caused: exec format error
frontend-rwsols exited with code 1
frontend-rwsols    | standard_init_linux.go:219: exec user process caused: exec format error
frontend-rwsols    | standard_init_linux.go:219: exec user process caused: exec format error
frontend-rwsols    | standard_init_linux.go:219: exec user process caused: exec format error
frontend-rwsols    | standard_init_linux.go:219: exec user process caused: exec format error

```
