### ISSUE TITLE
Network host issue

### ISSUE THREAD

**Issue by 3th3r** [ex0nuss/Remote-Wake-Sleep-On-LAN-Docker#11]
Not working,

WoL working on other device but not on this service.
Problem with the network set as host.

**Comment by djismgaming** [comment]
Here's my working compose file:

``` yaml
services:
  RWSOL-Server:
    container_name: RWSOL-Server
    restart: unless-stopped
    entrypoint:
      - /entrypoint.sh
    environment:
      - TZ=America/Puerto_Rico
      - PASSPHRASE=
      - RWSOLS_COMPUTER_NAME=$RWSOLS_COMPUTER_NAME
      - RWSOLS_COMPUTER_MAC=$RWSOLS_COMPUTER_MAC
      - RWSOLS_COMPUTER_IP=$RWSOLS_COMPUTER_IP
      - RWSOLS_MAX_PINGS=10
      - RWSOLS_SLEEP_TIME=5
      - RWSOLS_SLEEP_CMD=suspend
      - RWSOLS_SLEEP_PORT=7760
      - TCP_PORT_9999=9999
      - APACHE2_PORT=9999
    image: ex0nuss/remote-wake-sleep-on-lan-docker
    network_mode: host
```
