### ISSUE TITLE
exec format error

### ISSUE THREAD

**Issue by Holzhauer** [ex0nuss/Remote-Wake-Sleep-On-LAN-Docker#3]
Thanks for this project! When I run the RWSOL docker container on Rasbian with `docker-compose up`, I get 
`standard_init_linux.go:228: exec user process caused: exec format error`
Any ideas?

docker-compose.yml:
```
version: "3"

services:
  frontend-rwsols:
    image: ex0nuss/remote-wake-sleep-on-lan-docker
    container_name: frontend-rwsols
    restart: unless-stopped
    network_mode: host
    environment:
      - APACHE2_PORT=8089
      - PASSPHRASE=INES@work
      - RWSOLS_COMPUTER_NAME="RDP-Rechner"
      - RWSOLS_COMPUTER_MAC="A0:66:10:B8:2F:B1"
      - RWSOLS_COMPUTER_IP="141.51.123.30"
```
